language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor
    - $HOME/.local

matrix:
  include:
    - php: 5.6
    - php: 7.0
      env:
        - TEST_COVERAGE=true
    - php: 7.1

before_install:
# Set the GitHub OAuth token to make use of the 6000 per hour rate limit
 - mkdir -p ~/.composer
 - cp .travis.composer.json ~/.composer/config.json
# Update composer
 - composer self-update
# Install project
 - composer update --prefer-dist --dev

before_script:
 - mkdir -p build/logs

script:
 - cd tests
 - if [[ $TEST_COVERAGE == 'true' ]]; then phpdbg -qrr ../vendor/bin/phpunit --coverage-text --coverage-clover ../build/logs/clover.xml ; fi
 - if [[ $TEST_COVERAGE != 'true' ]]; then ../vendor/bin/phpunit ; fi
 - cd ..

after_script:
 - if [[ $TEST_COVERAGE == 'true' ]]; php vendor/bin/coveralls --verbose --config ; fi
